spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notes
    username: notes
    password: notes
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update